src/objects/Kizuna_Candidate__c.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Volunteer</label>
    <nameField>
        <displayFormat>VL{00000000}</displayFormat>
        <label>V-Event</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Kizuna_CheckIn__c.object
<CustomObject>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Participant</label>
        <referenceTo>Kizuna_Participant__c</referenceTo>
        <relationshipLabel>Check-In</relationshipLabel>
        <relationshipName>CheckIns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Check-In</label>
    <nameField>
        <displayFormat>CI{00000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Kizuna_Participant__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Kizuna_Candidate__c</referenceTo>
        <relationshipName>Participants</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>NumberOfCheckin__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number Of Checkin</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <formula>NumberOfCheckin__c &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Participant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <formula>Volunteer__r.StartDate__c</formula>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Volunteer__c</fullName>
        <label>Volunteer</label>
        <referenceTo>Kizuna_Volunteer__c</referenceTo>
        <relationshipName>Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Participate</label>
    <nameField>
        <displayFormat>PT{00000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Kizuna_Request__c.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>SP{00000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Kizuna_Volunteer__c.object
<CustomObject>
    <fields>
        <fullName>NumberOfCheckin__c</fullName>
        <label>Number Of Checkin</label>
        <summarizedField>Kizuna_Participant__c.NumberOfCheckin__c</summarizedField>
        <summaryForeignKey>Kizuna_Participant__c.Volunteer__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request</label>
        <referenceTo>Kizuna_Request__c</referenceTo>
        <relationshipName>Volunteers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>V-Event</label>
    <nameField>
        <label>V-Event</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Kizuna_CheckInCountTriggerTest.cls
@isTest
private class Kizuna_CheckInCountTriggerTest {
    static Id createParticipantData() {
        Kizuna_Request__c request = new Kizuna_Request__c(
            LastName__c = 'test',
            FirstName__c = 'test'
        );
        insert request;

        Kizuna_Volunteer__c volunteer = new Kizuna_Volunteer__c(
            Request__c = request.Id,
            StartDate__c = Date.today()
        );
        insert volunteer;

        Kizuna_Candidate__c candidate = new Kizuna_Candidate__c(
            LastName__c = 'test',
            FirstName__c = 'test'
        );
        insert candidate;

        Kizuna_Participant__c participant = new Kizuna_Participant__c(
            Volunteer__c = volunteer.Id,
            Candidate__c = candidate.Id
        );
        insert participant;

        return participant.Id;
    }

    static testMethod void insertTest() {
        // init
        ID pid = createParticipantData();

        // test
        Test.startTest();
        Kizuna_CheckIn__c checkin1 = new Kizuna_CheckIn__c(
            Participant__c = pid
        );
        insert checkin1;
        Kizuna_CheckIn__c checkin2 = new Kizuna_CheckIn__c(
            Participant__c = pid
        );
        insert checkin2;
        Test.stopTest();

        // check
        Kizuna_Participant__c p = [Select NumberOfCheckin__c From Kizuna_Participant__c Where Id = :pid];
        System.assertEquals(2, p.NumberOfCheckin__c);
    }

    static testMethod void deleteTest() {
        // init
        ID pid = createParticipantData();

        Kizuna_CheckIn__c checkin1 = new Kizuna_CheckIn__c(
            Participant__c = pid
        );
        insert checkin1;
        Kizuna_CheckIn__c checkin2 = new Kizuna_CheckIn__c(
            Participant__c = pid
        );
        insert checkin2;

        // test
        Test.startTest();
        delete checkin1;
        delete checkin2;
        Test.stopTest();

        // check
        Kizuna_Participant__c p = [Select NumberOfCheckin__c From Kizuna_Participant__c Where Id = :pid];
        System.assertEquals(0, p.NumberOfCheckin__c);
    }
}